Install script now copies textures

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,3 +4,8 @@ mkdir build
 cd build
 cmake ..
 make
+if [ ! -d `pwd`/build/src ]; then
+    echo "GoldMiner file not found. Run 'install' script first."
+    exit 1
+fi
+cp * `pwd`/sprites `pwd`/build/src
